build:
 version: "1.0"

cards:
  message: "Welcome to EazyBank accounts related prod APIs "
  contactDetails:
    name: "Reine Akash - Product Owner"
    email: "aishwarya@eazybank.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384