spring:
  application:
    name: "eurekaserver"

  config:
    import: "optional:configserver:http://localhost:8071"


management:
  endpoints:
    web:
      exposure:
        include: "*"

  health:
    readiness-state:
      enable: true
    liveness-state:
      enable: true
    endpoint:
      health:
        probes:
          enable: true
